# Generated by Django 4.0.4 on 2024-08-31 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backone', '0036_remove_backone_orbit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DscDpiStatQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=30, verbose_name='MSISDN')),
                ('quota', models.IntegerField()),
                ('quota_string', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DPI Statistic',
                'verbose_name_plural': 'DPI Statistics',
                'db_table': 'dscdpi_stat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DscDpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=30, verbose_name='MSISDN')),
                ('imei', models.CharField(blank=True, max_length=30, verbose_name='IMEI')),
                ('quota_total', models.CharField(blank=True, max_length=20, verbose_name='Kuota Total')),
                ('quota_current', models.CharField(blank=True, max_length=20, verbose_name='Kuota Saat Ini')),
                ('quota_until', models.CharField(blank=True, max_length=20, verbose_name='Kuota Masa Berlaku ')),
                ('quota_prev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quota Prev')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('error_msg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backone.backone', verbose_name='Site')),
            ],
            options={
                'verbose_name_plural': 'Daftar DPI',
                'db_table': 'dscdpi',
                'managed': True,
            },
        ),
    ]
