# Generated by Django 4.2.15 on 2024-09-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dscdpi',
            options={'managed': True, 'verbose_name': 'DPI', 'verbose_name_plural': 'Daftar DPI'},
        ),
        migrations.AddField(
            model_name='dscdpi',
            name='quota_date',
            field=models.DateField(blank=True, null=True, verbose_name='Berlaku Sampai'),
        ),
        migrations.AddField(
            model_name='dscdpi',
            name='quota_day',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kuota Hari'),
        ),
    ]
