# Generated by Django 4.2.15 on 2024-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0002_alter_dscdpi_options_dscdpi_quota_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dscdpi',
            name='quota_type',
            field=models.CharField(default='dpi', max_length=20, verbose_name='Quota Type'),
        ),
        migrations.AlterField(
            model_name='dscdpi',
            name='quota_total',
            field=models.CharField(blank=True, default='5 GB', max_length=20, verbose_name='Kuota Total'),
        ),
    ]
