# Generated by Django 4.2.15 on 2024-10-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0003_dscdpi_quota_type_alter_dscdpi_quota_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscdpi',
            name='msisdn',
            field=models.CharField(max_length=30, unique=True, verbose_name='MSISDN'),
        ),
    ]
