# Generated by Django 4.2.15 on 2024-10-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0004_alter_dscdpi_msisdn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DscDpiProit',
            fields=[
                ('dscdpi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dsc.dscdpi')),
            ],
            options={
                'verbose_name': 'DPI Proit',
                'verbose_name_plural': 'Daftar DPI Proit',
                'db_table': 'dscdpi_proit',
                'managed': True,
            },
            bases=('dsc.dscdpi',),
        ),
    ]
