# Generated by Django 4.2.15 on 2024-10-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0005_dscdpiproit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DscDpiProit',
        ),
    ]
