# Generated by Django 4.2.15 on 2024-10-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0036_remove_backone_orbit'),
        ('dsc', '0006_delete_dscdpiproit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DscDpiProit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=30, unique=True, verbose_name='MSISDN')),
                ('imei', models.CharField(blank=True, max_length=30, verbose_name='IMEI')),
                ('quota_total', models.CharField(blank=True, default='5 GB', max_length=20, verbose_name='Kuota Total')),
                ('quota_current', models.CharField(blank=True, max_length=20, verbose_name='Kuota Saat Ini')),
                ('quota_until', models.CharField(blank=True, max_length=20, verbose_name='Kuota Masa Berlaku ')),
                ('quota_date', models.DateField(blank=True, null=True, verbose_name='Berlaku Sampai')),
                ('quota_day', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kuota Hari')),
                ('quota_prev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quota Prev')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('error_msg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Error Message')),
                ('quota_type', models.CharField(default='dpi', max_length=20, verbose_name='Quota Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backone.backone', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'DPI Proit',
                'verbose_name_plural': 'Daftar DPI Proit',
                'db_table': 'dscdpi_proit',
                'managed': True,
            },
        ),
    ]
