# Generated by Django 4.0.4 on 2022-06-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True, 'verbose_name_plural': 'Daftar Kontak'},
        ),
    ]
