# Generated by Django 4.0.4 on 2022-11-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Map Statistic',
                'verbose_name_plural': ' Map Statistics',
            },
        ),
    ]
