# Generated by Django 4.2.15 on 2024-09-09 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telkomsat', '0002_starlink_kit_serialnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starlink',
            name='activation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 9, 8, 28, 8, 942924, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Aktivasi'),
        ),
    ]
