# Generated by Django 4.2.15 on 2024-09-10 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telkomsat', '0003_starlink_activation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starlink',
            old_name='service_line_number',
            new_name='msisdn',
        ),
        migrations.AlterField(
            model_name='starlink',
            name='activation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 10, 8, 55, 0, 809795, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Aktivasi'),
        ),
    ]
