# Generated by Django 4.2.15 on 2024-10-21 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telkomsat', '0008_alter_starlink_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starlink',
            name='activation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 21, 23, 34, 45, 367610, tzinfo=datetime.timezone.utc), verbose_name='Tanggal Aktivasi'),
        ),
    ]
