# Generated by Django 4.2.15 on 2024-10-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telkomsat', '0009_alter_starlink_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starlink',
            name='activation_date',
            field=models.DateField(blank=True, verbose_name='Tanggal Aktivasi'),
        ),
    ]
