# Generated by Django 4.0.4 on 2022-06-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_servicetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'managed': True, 'verbose_name_plural': 'Layanan Yang Dijual'},
        ),
        migrations.AlterModelOptions(
            name='servicevendor',
            options={'managed': True, 'verbose_name_plural': 'Layanan Yang Dibeli'},
        ),
    ]
