# Generated by Django 4.0.4 on 2022-05-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('msisdn', models.CharField(max_length=30)),
                ('imei', models.CharField(max_length=30)),
                ('quota_total', models.CharField(blank=True, max_length=20)),
                ('quota_current', models.CharField(blank=True, max_length=20)),
                ('quota_day', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orbit',
                'managed': True,
            },
        ),
    ]
