# Generated by Django 4.0.4 on 2022-05-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orbit',
            options={'managed': True, 'verbose_name_plural': 'orbits'},
        ),
    ]
