# Generated by Django 4.0.4 on 2022-06-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0003_alter_orbit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orbit',
            options={'managed': True, 'verbose_name_plural': 'Daftar Orbit'},
        ),
    ]
