# Generated by Django 4.0.4 on 2022-11-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0006_alter_orbit_quota_current_alter_orbit_quota_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbit',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
    ]
