# Generated by Django 4.0.4 on 2022-11-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0036_remove_backone_orbit'),
        ('orbit', '0007_orbit_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbit',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backone.backone', verbose_name='Site'),
        ),
    ]
