# Generated by Django 4.0.4 on 2023-10-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0010_orbitstatquota_alter_orbitmulti_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitstatquota',
            name='quota_string',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
