# Generated by Django 4.0.4 on 2023-10-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0012_orbit_quota_prev_orbitmulti_quota_prev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitstatquota',
            name='quota_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
