# Generated by Django 4.2.15 on 2024-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0013_alter_orbitstatquota_quota_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbit',
            name='quota_type',
            field=models.CharField(default='orbit', max_length=20, verbose_name='Quota Type'),
        ),
        migrations.AddField(
            model_name='orbitmulti',
            name='quota_type',
            field=models.CharField(default='orbit', max_length=20, verbose_name='Quota Type'),
        ),
    ]
