# Generated by Django 4.2.15 on 2025-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0014_orbit_quota_type_orbitmulti_quota_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbit',
            name='quota_day',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kuota Hari'),
        ),
    ]
