# Generated by Django 4.2.20 on 2025-04-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0015_alter_orbit_quota_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbit',
            name='error_msg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Error Message'),
        ),
    ]
