# Generated by Django 4.0.4 on 2022-05-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orbit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ipaddress', models.GenericIPAddressField(default='0.0.0.0')),
                ('username', models.CharField(default='root', max_length=20)),
                ('password', models.CharField(default='K0l0r1j0', max_length=20)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('backone_network', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orbit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orbit.orbit')),
            ],
            options={
                'db_table': 'backone',
                'managed': True,
            },
        ),
    ]
