# Generated by Django 4.0.4 on 2022-05-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backone',
            options={'managed': True, 'verbose_name_plural': 'backones'},
        ),
        migrations.AddField(
            model_name='backone',
            name='serial_number',
            field=models.CharField(default='000000000', max_length=30),
        ),
    ]
