# Generated by Django 4.0.4 on 2022-05-24 17:22

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0003_alter_backone_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='backone',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100),
        ),
    ]
