# Generated by Django 4.0.4 on 2022-05-24 17:43

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0005_alter_backone_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backone',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100),
        ),
    ]
