# Generated by Django 4.0.4 on 2022-05-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0007_backone_sid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
