# Generated by Django 4.0.4 on 2022-05-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0008_backone_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backone',
            old_name='sid_number',
            new_name='sid',
        ),
    ]
