# Generated by Django 4.0.4 on 2022-05-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0009_rename_sid_number_backone_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backone',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
