# Generated by Django 4.0.4 on 2022-05-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
        ('backone', '0010_alter_backone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='connection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='connection.connectiontype'),
        ),
    ]
