# Generated by Django 4.0.4 on 2022-05-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0013_backone_connection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backone',
            name='is_active',
        ),
    ]
