# Generated by Django 4.0.4 on 2022-05-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0015_backone_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backone',
            name='location',
        ),
    ]
