# Generated by Django 4.0.4 on 2022-05-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('backone', '0016_remove_backone_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contact.contact'),
        ),
    ]
