# Generated by Django 4.0.4 on 2022-05-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicevendor_remove_servicetype_cost_installation_and_more'),
        ('backone', '0017_backone_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='service_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.servicevendor'),
        ),
    ]
