# Generated by Django 4.0.4 on 2022-05-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('connection', '0004_alter_connectionstatus_options_and_more'),
        ('service', '0003_servicevendor_remove_servicetype_cost_installation_and_more'),
        ('orbit', '0002_alter_orbit_options'),
        ('backone', '0018_backone_service_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backone',
            name='connection_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connection.connectionstatus'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='connection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connection.connectiontype'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='orbit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbit.orbit'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicetype'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='service_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicevendor'),
        ),
    ]
