# Generated by Django 4.0.4 on 2022-05-29 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('backone', '0019_alter_backone_connection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.po'),
        ),
        migrations.AddField(
            model_name='backone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
