# Generated by Django 4.0.4 on 2022-05-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0021_backone_baso_alter_backone_connection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='ipaddress_local',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
