# Generated by Django 4.0.4 on 2022-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0022_backone_ipaddress_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='backone_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
