# Generated by Django 4.0.4 on 2022-06-07 04:38

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0003_alter_orbit_options'),
        ('service', '0004_alter_servicetype_options_and_more'),
        ('connection', '0005_alter_connectionstatus_options_and_more'),
        ('project', '0007_alter_po_options_alter_project_options'),
        ('baso', '0003_alter_baso_options'),
        ('contact', '0002_alter_contact_options'),
        ('backone', '0023_backone_backone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backone',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='backone_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='SDWAN ID Site'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='backone_network',
            field=models.CharField(blank=True, max_length=50, verbose_name='SDWAN ID Network'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='baso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='baso.baso', verbose_name='Nomor BASO'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='connection_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='connection.connectionstatus', verbose_name='Status Koneksi'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='connection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='connection.connectiontype', verbose_name='Jenis Koneksi'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='contact.contact', verbose_name='Kontak di Site'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='description',
            field=models.TextField(blank=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='ipaddress',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='ipaddress_local',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP Address Lokal'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nama Site'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='orbit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='orbit.orbit', verbose_name='Koneksi Orbit'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='project.po', verbose_name='Nomor PO'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='project.project', verbose_name='Nama Project'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='serial_number',
            field=models.CharField(default='000000000', max_length=30, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='service.servicetype', verbose_name='Tipe Layanan'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='service_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='service.servicevendor', verbose_name='Vendor Layanan'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='sid',
            field=models.CharField(default='000000000', max_length=20, verbose_name='SID'),
        ),
    ]
