# Generated by Django 4.0.4 on 2022-06-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_servicetype_options_and_more'),
        ('backone', '0024_alter_backone_address_alter_backone_backone_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backone',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='service.servicetype', verbose_name='Tipe Layanan Yang Dijual'),
        ),
        migrations.AlterField(
            model_name='backone',
            name='service_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='service.servicevendor', verbose_name='Layanan Yang dibeli dari Vendor'),
        ),
    ]
