# Generated by Django 4.0.4 on 2022-06-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_po_options_alter_project_options'),
        ('backone', '0025_alter_backone_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backone',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='project.po', verbose_name='Nomor PO dari Customer'),
        ),
    ]
