# Generated by Django 4.0.4 on 2022-06-07 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_po_options_alter_project_options_alter_po_date_and_more'),
        ('backone', '0027_alter_backone_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='po_number_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='project.povendor', verbose_name='Nomor PO ke Vendor'),
        ),
    ]
