# Generated by Django 4.0.4 on 2022-06-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0028_backone_po_number_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backone',
            options={'managed': True, 'verbose_name': 'site', 'verbose_name_plural': 'Daftar Sites'},
        ),
    ]
