# Generated by Django 4.0.4 on 2022-06-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0032_backone_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='baso_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
