# Generated by Django 4.0.4 on 2022-06-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0033_backone_baso_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backone',
            name='baso_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal BASO'),
        ),
    ]
