# Generated by Django 4.0.4 on 2022-07-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backone', '0034_alter_backone_baso_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backone',
            name='ping_status',
            field=models.BooleanField(default=False, verbose_name='Ping Status'),
        ),
    ]
