# Generated by Django 4.0.4 on 2022-05-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baso',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='baso'),
        ),
    ]
