# Generated by Django 4.0.4 on 2022-06-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baso', '0002_alter_baso_upload_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baso',
            options={'managed': True, 'verbose_name_plural': 'Baso Lists'},
        ),
    ]
