# Generated by Django 4.0.4 on 2022-06-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baso', '0003_alter_baso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baso',
            options={'managed': True, 'verbose_name_plural': 'Daftar Baso'},
        ),
    ]
