# Generated by Django 4.0.4 on 2022-05-29 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='po_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
