# Generated by Django 4.0.4 on 2022-05-29 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_po_po_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project.project'),
        ),
    ]
