# Generated by Django 4.0.4 on 2022-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_contact_email_project_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='po'),
        ),
    ]
