# Generated by Django 4.0.4 on 2022-06-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_po_date_po_date_rename_po_number_po_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='po',
            options={'managed': True, 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'verbose_name_plural': 'Project Lists'},
        ),
    ]
