# Generated by Django 4.0.4 on 2022-06-07 05:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_po_options_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='po',
            options={'managed': True, 'verbose_name': 'Daftar PO dari Pelanggan', 'verbose_name_plural': 'Daftar PO dari Pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'verbose_name_plural': 'Daftar Project'},
        ),
        migrations.AlterField(
            model_name='po',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal PO'),
        ),
        migrations.AlterField(
            model_name='po',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nomor PO'),
        ),
        migrations.AlterField(
            model_name='po',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project.project', verbose_name='Nama Project'),
        ),
        migrations.AlterField(
            model_name='po',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='po', verbose_name='Document PO Upload'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Kontak'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nama Kontak Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telpon/HP Kontak'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nama Project (Unik)'),
        ),
        migrations.CreateModel(
            name='PoVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Nomor PO')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal PO')),
                ('upload_file', models.FileField(blank=True, upload_to='po_vendor', verbose_name='Document PO Upload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project.project', verbose_name='Nama Project')),
            ],
            options={
                'verbose_name': 'Daftar PO ke Vendor',
                'verbose_name_plural': 'Daftar PO ke Vendor',
                'db_table': 'po_vendor',
                'managed': True,
            },
        ),
    ]
