# Generated by Django 4.0.4 on 2022-06-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_po_options_alter_project_options_alter_po_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='povendor',
            name='project',
        ),
        migrations.AddField(
            model_name='povendor',
            name='po_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='project.po', verbose_name='Landasan PO dari Pelanggan'),
        ),
    ]
