# Generated by Django 4.0.4 on 2022-06-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_po_is_new_po_is_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='PO Baru'),
        ),
    ]
