# Generated by Django 4.0.4 on 2022-06-07 05:48

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama PT')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Singkatan Nama PT')),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='Alamat')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daftar PT Kita',
                'verbose_name_plural': 'Daftar PT Kita',
                'db_table': 'my_company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OtherCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama PT')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Singkatan Nama PT')),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='Alamat')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daftar PT Pelanggan/Vendor',
                'verbose_name_plural': 'Daftar PT Pelanggan/Vendor',
                'db_table': 'other_company',
                'managed': True,
            },
        ),
    ]
