# Generated by Django 4.0.4 on 2022-06-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='othercompany',
            options={'managed': True, 'verbose_name': 'Daftar PT Client/Vendor', 'verbose_name_plural': 'Daftar PT Client/Vendor'},
        ),
    ]
